baseurl: 'https://emilycodeee.github.io/'
title: Emily is coding
theme: hugo-theme-cleanwhite
languageCode: zh-tw
disqusShortname: ''
googleAnalytics: ''
preserveTaxonomyNames: true
paginate: 7
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  header_image: img/home-bg-jeep.jpg
  SEOTitle: Emilydondon Blog
  description: ''
  keyword: 
  slogan: ''
  image_404: img/404-bg.jpg
  title_404: '你不小心來到了一個神秘的、沒有知識的荒原 :('
  omit_categories: false
  page_view_conter: false
  leancloud_app_id: ''
  leancloud_app_key: ''
  algolia_search: true
  algolia_appId: ''
  algolia_indexName: ''
  algolia_apiKey: ''
  sidebar_about_description: 'Front-End Developer and Life Adventurer'
  # sidebar_avatar: img/emily.jpg
  featured_tags: true
  featured_condition_size: 1
  ba_track_id: ''
  disqus_proxy: ''
  disqus_site: ''
  twikoo_env_id: ''
  reward: true
  friends: true
  bookmarks: true
  about_me: true
  social:
    rss: true
    email: emilydondon@gmail.com
    linkedin: 'https://www.linkedin.com/in/emily-chen-emilydondon'
    # stackoverflow: 'https://stackoverflow.com/users/yourstackoverflowid'
    github: 'https://github.com/emilycodeee'
    # wechat: your wechat qr code image
  # friend_link:
  #   - title: Linda的博客
  #     href: 'https://zhaozhihan.com'
  bookmark_link:
    # - title: Martin Fowler
    #   href: 'https://martinfowler.com'
    # - title: ServiceMesher
    #   href: 'http://www.servicemesher.com'
    # - title: Pxhere
    #   href: 'https://pxhere.com'
    # - title: unsplash
    #   href: 'https://unsplash.com'
  addtional_menus:
    # - title: ARCHIVE
    #   href: /archive/
    # - title: NOTES
    #   href: /notes/
    # - title: ABOUT
    #   href: /about/
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
